package backends

import backends.Verilog.*
import ir.rtl.RAMControl
import ir.rtl.hardwaretype.{ComplexHW, HW}
import maths.fields.Complex
import transforms.fft.{CTDFT, TangentTwistAfterSwitch}
import transforms.perm.SwitchTranspose

/** Rate-preserving FPT tangent FFT for laneLog >= cycleLog.
  * Splits the K-wide input into K/C independent CxC switch-transpose blocks.
  * Each block has its own correctly strided tangent-twiddle path, and the
  * reverse blocks are packed back into the original K-wide FFT input.
  */
object FptParallelSwitchTangentVerilog:
  private def renameTop(rtl: String, name: String): String = rtl.replaceFirst("module main\\(", s"module $name(")

  def emit(n: Int, r: Int, laneLog: Int, hw: ComplexHW[Double], scalingFactor: Complex[Double], top: String = "main"): String =
    val cycleLog = n - laneLog
    require(cycleLog >= 0 && laneLog >= cycleLog && laneLog < n)
    require(top.matches("[A-Za-z_][A-Za-z0-9_$]*"))
    given HW[Complex[Double]] = hw
    val blockLog = cycleLog
    val blockWidth = 1 << blockLog
    val blocks = 1 << (laneLog - blockLog)
    val inputLanes = 1 << laneLog
    val width = hw.size
    val switchName = s"${top}SquareSwitch"
    val switchRtl = renameTop(SwitchTranspose[Complex[Double]](blockLog).stream(blockLog, RAMControl.Single).toVerilog, switchName)
    val twistRtls = (0 until blocks).map { block =>
      val twist = TangentTwistAfterSwitch(n, blockLog, inverse = false, laneStride = blocks, cycleOffset = block * blockWidth, cycleLog = blockLog)
      renameTop(twist.stream(blockLog, RAMControl.Single).toVerilog, s"${top}Twist$block")
    }.mkString("\n")
    val fftName = s"${top}ForwardCore"
    val fftRtl = renameTop(CTDFT(n, r, scalingFactor).stream(laneLog, RAMControl.Single).toVerilog, fftName)
    val inputs = Vector.tabulate(inputLanes)(lane => s"input [${width - 1}:0] i$lane")
    val outputs = Vector.tabulate(inputLanes)(lane => s"output [${width - 1}:0] o$lane")
    val wires = (0 until blocks).flatMap { block =>
      Vector(s"wire pre_next_$block,twist_next_$block,post_next_$block;") ++
        Vector.tabulate(blockWidth)(lane => s"wire [${width - 1}:0] pre_${block}_$lane,twist_${block}_$lane,post_${block}_$lane;")
    }
    def connections(prefix: String, values: String => String): Vector[String] =
      Vector.tabulate(blockWidth)(lane => s".$prefix$lane(${values(lane.toString)})")
    val blocksRtl = (0 until blocks).flatMap { block =>
      val preAt = (lane: String) => s"pre_${block}_$lane"
      val twistAt = (lane: String) => s"twist_${block}_$lane"
      val postAt = (lane: String) => s"post_${block}_$lane"
      Vector(
        s"$switchName pre_$block(.clk(clk),.reset(reset),.next(next),.next_out(pre_next_$block),${Vector.tabulate(blockWidth)(lane => s".i$lane(i${block * blockWidth + lane})").mkString(",")},${connections("o", preAt).mkString(",")});",
        s"${top}Twist$block twist_$block(.clk(clk),.reset(reset),.next(pre_next_$block),.next_out(twist_next_$block),${connections("i", preAt).mkString(",")},${connections("o", twistAt).mkString(",")});",
        s"$switchName post_$block(.clk(clk),.reset(reset),.next(twist_next_$block),.next_out(post_next_$block),${connections("i", twistAt).mkString(",")},${connections("o", postAt).mkString(",")});"
      )
    }.mkString("\n  ")
    val fftInputs = Vector.tabulate(inputLanes) { lane =>
      val block = lane / blockWidth
      val local = lane % blockWidth
      s".i$lane(post_${block}_$local)"
    }
    val fftOutputs = Vector.tabulate(inputLanes)(lane => s".o$lane(o$lane)")
    s"""// Generated by SGen rate-preserving parallel switch FPT tangent FFT.
       |// $blocks parallel ${blockWidth}x${blockWidth} switch/twist blocks retain $inputLanes external lanes.
       |$switchRtl
       |$twistRtls
       |$fftRtl
       |module $top(input clk,input reset,input next,output next_out,
       |${(inputs ++ outputs).map("  " + _).mkString(",\n")}
       |);
       |${wires.map("  " + _).mkString("\n")}
       |  $blocksRtl
       |  $fftName fft(.clk(clk),.reset(reset),.next(post_next_0),.next_out(next_out),${fftInputs.mkString(",")},${fftOutputs.mkString(",")});
       |endmodule
       |""".stripMargin
