package backends

/** Width-changing lane/time transpose for the SGen terminal interface.
  *
  * Input:  2^cycleLog cycles of 2^laneLog values.
  * Output: 2^laneLog cycles of 2^cycleLog values.
  *
  * The square case remains implemented by SGen's recursive SwitchTransposeUnit
  * network.  Rectangular shapes require a width adapter and therefore retain
  * one tensor while the opposite dimension is serialized.
  */
object RectangularSwitchTransposeVerilog:
  def emit(cycleLog:Int,laneLog:Int,dataWidth:Int,top:String="switchtranspose"):String=
    require(cycleLog>=0&&laneLog>=0&&cycleLog+laneLog>0&&dataWidth>0)
    require(top.matches("[A-Za-z_][A-Za-z0-9_$]*"))
    val cycles=1<<cycleLog
    val lanes=1<<laneLog
    val outputAssignments=Vector.tabulate(cycles){lane=>
      s"o$lane<=storage[$lane*$lanes+output_count];"
    }.mkString(" ")
    val captureAssignments=Vector.tabulate(lanes){lane=>
      s"storage[input_count*$lanes+$lane]<=i$lane;"
    }.mkString(" ")
    val inputs=Vector.tabulate(lanes)(lane=>s"input [${dataWidth-1}:0] i$lane")
    val outputs=Vector.tabulate(cycles)(lane=>s"output reg [${dataWidth-1}:0] o$lane")
    s"""// Generated by SGen rectangular SwitchTranspose adapter.
       |// Exchanges ${cycles} temporal cycles with $lanes spatial lanes.
       |module $top(input clk,input reset,input next,output reg next_out,
       |${(inputs++outputs).map("  "+_).mkString(",\n")}
       |);
       |  localparam integer INPUT_CYCLES=$cycles,INPUT_LANES=$lanes,OUTPUT_CYCLES=$lanes,OUTPUT_LANES=$cycles;
       |  reg [${dataWidth-1}:0] storage [0:${cycles*lanes-1}];reg input_active,output_active;integer input_count,output_count,index;
       |  always @(posedge clk) begin
       |    if(reset) begin input_active<=0;output_active<=0;input_count<=0;output_count<=0;next_out<=0;for(index=0;index<INPUT_CYCLES*INPUT_LANES;index=index+1)storage[index]<=0;end
       |    else begin
       |      next_out<=0;
       |      if(next||input_active) begin
       |        $captureAssignments
       |        if(input_count==INPUT_CYCLES-1)begin input_count<=0;input_active<=0;output_active<=1;output_count<=0;end else begin input_count<=input_count+1;input_active<=1;end
       |      end else if(output_active) begin
       |        $outputAssignments
       |        if(output_count==0)next_out<=1;
       |        if(output_count==OUTPUT_CYCLES-1)begin output_count<=0;output_active<=0;end else output_count<=output_count+1;
       |      end
       |    end
       |  end
       |endmodule
       |""".stripMargin
