package backends

/** Width-changing lane/time transpose for the SGen terminal interface.
  *
  * Input:  2^cycleLog cycles of 2^laneLog values.
  * Output: 2^laneLog cycles of 2^cycleLog values.
  *
  * The square case remains implemented by SGen's recursive SwitchTransposeUnit
  * network.  Rectangular shapes require a width adapter and therefore retain
  * one tensor while the opposite dimension is serialized.
  */
object RectangularSwitchTransposeVerilog:
  def emit(cycleLog:Int,laneLog:Int,dataWidth:Int,top:String="switchtranspose"):String=
    require(cycleLog>=0&&laneLog>=0&&cycleLog+laneLog>0&&dataWidth>0)
    require(top.matches("[A-Za-z_][A-Za-z0-9_$]*"))
    val cycles=1<<cycleLog
    val lanes=1<<laneLog
    val outputAssignments=(buffer:Int)=>Vector.tabulate(cycles){lane=>
      s"o$lane<=storage_$buffer[$lane*$lanes+output_count];"
    }.mkString(" ")
    val captureAssignments=(buffer:Int)=>Vector.tabulate(lanes){lane=>
      s"storage_$buffer[input_count*$lanes+$lane]<=i$lane;"
    }.mkString(" ")
    val inputs=Vector.tabulate(lanes)(lane=>s"input [${dataWidth-1}:0] i$lane")
    val outputs=Vector.tabulate(cycles)(lane=>s"output reg [${dataWidth-1}:0] o$lane")
    s"""// Generated by SGen rectangular SwitchTranspose adapter.
       |// Exchanges ${cycles} temporal cycles with $lanes spatial lanes.
       |module $top(input clk,input reset,input next,output ready,output reg next_out,
       |${(inputs++outputs).map("  "+_).mkString(",\n")}
       |);
       |  localparam integer INPUT_CYCLES=$cycles,INPUT_LANES=$lanes,OUTPUT_CYCLES=$lanes,OUTPUT_LANES=$cycles;
       |  localparam [1:0] FREE=0,CAPTURE=1,QUEUED=2,OUTPUT=3;
       |  reg [1:0] buffer_state [0:1];reg input_active,input_buffer,output_active,output_buffer;reg [${dataWidth-1}:0] storage_0 [0:${cycles*lanes-1}],storage_1 [0:${cycles*lanes-1}];integer input_count,output_count,index;
       |  assign ready=!input_active&&((buffer_state[0]==FREE)||(buffer_state[1]==FREE));
       |  always @(posedge clk) begin
       |    if(reset) begin input_active<=0;input_buffer<=0;output_active<=0;output_buffer<=0;input_count<=0;output_count<=0;next_out<=0;buffer_state[0]<=FREE;buffer_state[1]<=FREE;for(index=0;index<INPUT_CYCLES*INPUT_LANES;index=index+1)begin storage_0[index]<=0;storage_1[index]<=0;end end
       |    else begin
       |      next_out<=0;
       |      if((next&&ready)||input_active) begin
       |        if(!input_active) begin
       |          if(buffer_state[0]==FREE) begin ${captureAssignments(0)} buffer_state[0]<=CAPTURE;input_buffer<=0;end
       |          else begin ${captureAssignments(1)} buffer_state[1]<=CAPTURE;input_buffer<=1;end
       |          input_active<=1;
       |        end else if(input_buffer==0) begin ${captureAssignments(0)} end else begin ${captureAssignments(1)} end
       |        if(input_count==INPUT_CYCLES-1)begin if(input_active?input_buffer:(buffer_state[0]==FREE?0:1))buffer_state[1]<=QUEUED;else buffer_state[0]<=QUEUED;input_count<=0;input_active<=0;end else begin input_count<=input_count+1;end
       |      end
       |      if(output_active) begin
       |        if(output_buffer==0)begin ${outputAssignments(0)} end else begin ${outputAssignments(1)} end
       |        if(output_count==0)next_out<=1;
       |        if(output_count==OUTPUT_CYCLES-1)begin if(output_buffer==0)buffer_state[0]<=FREE;else buffer_state[1]<=FREE;output_count<=0;output_active<=0;end else output_count<=output_count+1;
       |      end else if(buffer_state[0]==QUEUED) begin buffer_state[0]<=OUTPUT;output_buffer<=0;output_active<=1;output_count<=0;
       |      end else if(buffer_state[1]==QUEUED) begin buffer_state[1]<=OUTPUT;output_buffer<=1;output_active<=1;output_count<=0;
       |      end
       |    end
       |  end
       |endmodule
       |""".stripMargin
